apiVersion: v1
kind: Service
metadata:
  name: diva-backend
  namespace: diva
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: http
      nodePort: 30012
      name: http
  selector:
    app: diva-backend
