apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: diva
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://100.120.207.67:30529/castle96/esp-flash-api.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: diva
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
